import type { EvaluationView, ObservationView, WorkspaceView } from '@ptcg/contracts';
import { decisionLabel } from '@ptcg/contracts';
import { Chip, Empty, Field, Observation, Section, time, words } from './components.js';
export function Opportunities({ data, select, selected, open }: { readonly data: WorkspaceView; readonly select: (id: string) => void; readonly selected: EvaluationView | null; readonly open: (id: string) => void; }) {
  return <><Section title="Opportunity evaluations"><p className="muted">Seller approval, opportunity eligibility and simulation decisions are evaluated separately. Historical results do not authorize a new action.</p>
    {!data.evaluations.length ? <Empty>No evaluations yet. Run an enabled monitor to inspect evidence and blocking reasons.</Empty> : <div className="table-scroll"><table><thead><tr><th>Product / variant</th><th>Price / stock</th><th>Seller at evaluation</th><th>Opportunity</th><th>DRY RUN</th><th>Evidence</th></tr></thead><tbody>{data.evaluations.map(e => <tr key={e.id}><td><button className="text-button" onClick={() => select(e.id)}>{e.observation.title}</button><small>{e.observation.variant} · Kantocards</small></td><td><Field field={e.observation.price} /><small><Field field={e.observation.stock} /></small></td><td><Chip value={e.sellerStatus} /><small><Field field={e.observation.seller} /></small></td><td><Chip value={e.outcome} /><small>Mapping: {words(e.mapping)}</small></td><td>{decisionLabel(e.decision)}</td><td><Chip value={e.observation.stale ? 'STALE' : 'OBSERVED'} /><small>{time(e.observation.capturedAt)}</small></td></tr>)}</tbody></table></div>}</Section>
    {selected && <Section title="Evaluation detail"><div className="row"><h3>{decisionLabel(selected.decision)}</h3><Chip value={selected.outcome} /></div>
      <p>Seller {words(selected.sellerStatus)} at {time(selected.evaluatedAt)}. {selected.observation.stale ? 'This evidence is now stale.' : 'Evidence age is within the display freshness window.'}</p>
      <dl className="facts"><dt>Mapping</dt><dd>{words(selected.mapping)} · {selected.mapping === 'REVIEWED' ? 'Reviewed' : 'Needs Review'}</dd><dt>Landed cost</dt><dd><Field field={selected.landedCost} /></dd><dt>Benchmark</dt><dd><Field field={selected.benchmark} /></dd><dt>ROI / margin</dt><dd>{selected.roi ?? 'Unknown'} / {selected.margin ?? 'Unknown'}</dd><dt>Arithmetic</dt><dd>{words(selected.arithmetic)}</dd></dl>
      <h3>Decision checks</h3><ul className="checks">{selected.checks.map((c, i) => <li key={i}><Chip value={c.result} /> {words(c.code)}{c.field && ` · ${words(c.field)}`}{c.reason && <small>{words(c.reason)}</small>}</li>)}</ul>
      {selected.decisionEvaluationId && selected.decisionEvaluationId !== selected.id && <p className="notice">This observation retained the existing cycle decision. <button onClick={() => select(selected.decisionEvaluationId ?? selected.id)}>Inspect original decision evaluation</button></p>}
      <Observation value={selected.observation} open={open} /><details><summary>Decision trace</summary><p className="ids">Monitor {selected.monitorId}<br />Run {selected.runId}<br />Evaluation {selected.id}<br />Intent {selected.intentId ?? 'Not admitted'}</p></details>
    </Section>}</>;
}
export function Products({ data, history, select, open }: { readonly data: WorkspaceView; readonly history: readonly ObservationView[]; readonly select: (id: string) => void; readonly open: (id: string) => void; }) {
  return <><Section title="Latest product observations"><p className="muted">Store identity is preserved across reads. Mapping is shown with each evaluation; store identity alone does not establish a canonical product match.</p>{!data.products.length ? <Empty>No product observations. Unknown values remain unknown until observed.</Empty> : data.products.map(p => <div className="product-row" key={p.offerId}><div><strong>{p.title}</strong><small>{p.variant} · {time(p.capturedAt)} · {p.stale ? 'Stale' : 'Observed'}</small></div><Field field={p.price} /><button onClick={() => select(p.offerId)}>Observation history</button></div>)}</Section>
    {history.length > 0 && <Section title="Observation and price history">{history.map(p => <Observation key={p.id} value={p} open={open} />)}</Section>}</>;
}
export function History({ data, select }: { readonly data: WorkspaceView; readonly select: (id: string) => void; }) {
  return <Section title="Durable audit history">{!data.history.length ? <Empty>No decision audit events yet.</Empty> : <div className="table-scroll"><table><thead><tr><th>Time</th><th>Event</th><th>Mode / outbox</th><th>Trace</th></tr></thead><tbody>{data.history.map((h, i) => <tr key={i}><td>{time(h.at)}</td><td>{words(h.action)}</td><td>DRY RUN<small>Outbox: {h.outboxStatus ?? 'Not applicable'}</small></td><td>{h.evaluationId && <button onClick={() => select(h.evaluationId ?? '')}>Inspect evaluation</button>}<details><summary>Monitor → observation → decision</summary><p className="ids">{h.monitorId}<br />{h.runId}<br />{h.observationId}<br />{h.evaluationId}<br />{h.intentId}</p></details></td></tr>)}</tbody></table></div>}</Section>;
}
