import { useState } from 'react';
import type { MonitorInput, MonitorView, WorkspaceView } from '@ptcg/contracts';
import { Chip, Empty, Field, Section, time, words } from './components.js';
export function Monitors({ data, act }: { readonly data: WorkspaceView; readonly act: (operation: () => Promise<unknown>) => Promise<void>; }) {
  const [editing, setEditing] = useState<MonitorView | null>(null);
  const [name, setName] = useState(''); const [url, setUrl] = useState(''); const [cadence, setCadence] = useState(300);
  const [saving, setSaving] = useState(false);
  const begin = (m: MonitorView) => { setEditing(m); setName(m.name); setUrl(m.url); setCadence(m.cadenceSeconds); };
  const save = async () => {
    setSaving(true);
    try { await act(async () => { const input: MonitorInput = { name, url, cadenceSeconds: cadence }; const reply = editing ? await window.astra.updateMonitor({ ...input, id: editing.id, expectedVersion: editing.version }) : await window.astra.createMonitor(input); if (!reply.ok) throw new Error(`${words(reply.code)} · ${reply.diagnosticId}`); setEditing(null); setName(''); setUrl(''); }); } finally { setSaving(false); }
  };
  return <><Section title={editing ? 'Edit URL monitor' : 'Create URL monitor'}><p className="muted">Kantocards or Amazon Mexico · approved product URLs only. Read-only, DRY RUN. Active monitors run while the app is open, within the shared read budget.</p>
    <form onSubmit={event => { event.preventDefault(); void save(); }} className="monitor-form">
      <label>Name<input name="monitor-name" required maxLength={80} value={name} onChange={e => setName(e.target.value)} placeholder="Spanish booster observation" /></label>
      <label className="wide">Product URL<input name="monitor-url" required type="url" maxLength={2048} value={url} onChange={e => setUrl(e.target.value)} placeholder="https://kantocards.com/products/…" /></label>
      <label>Cadence (seconds)<input name="monitor-cadence" required type="number" min={60} max={86400} value={cadence} onChange={e => setCadence(Number(e.target.value))} /></label>
      <button className="primary" disabled={saving}>{saving ? 'Saving…' : editing ? 'Save revision' : 'Create monitor'}</button>{editing && <button type="button" onClick={() => { setEditing(null); setName(''); setUrl(''); }}>Cancel edit</button>}
    </form></Section>
    <Section title="URL monitors">{!data.monitors.length ? <Empty>No monitors yet. Add an authorized product URL to begin.</Empty> : <div className="table-scroll"><table><thead><tr><th>Monitor / normalized target</th><th>Status</th><th>Schedule</th><th>Latest read</th><th>Actions</th></tr></thead><tbody>{data.monitors.map(m => <tr key={m.id}><td><strong>{m.name}</strong><small className="url">{m.url}</small><small>{m.family ?? 'Shopify'} · {m.provider ?? 'SHOPIFY'} · {m.cadenceSeconds}s</small></td><td><Chip value={m.status} /><small>{words(data.stores.find(s => s.family === (m.family ?? 'Shopify'))?.observationHealth ?? 'UNKNOWN')}</small></td><td><small>Last: {time(m.lastRunAt)}</small><small>Next: {m.status === 'ACTIVE' ? time(m.nextDueAt) : 'Paused / archived'}</small></td><td>{m.latest ? <Field field={m.latest.price} /> : 'Unknown'}<small>Last attempt: {words(m.lastResult)}</small>{m.product && <details open><summary>{m.product.title}</summary><p>{m.product.asin} · {m.product.stale ? 'STALE — previous observation' : 'Fresh observation'}</p><p>Availability: <Field field={m.product.availability} /> · Purchase mode: <Field field={m.product.purchaseMode} /></p><p>Release: <Field field={m.product.releaseDate} /></p><p>Price: <Field field={m.product.price} /> · Seller: <Field field={m.product.seller} /> · Fulfillment: <Field field={m.product.fulfillment} /></p><p>Observed: {time(m.product.observedAt)} · {m.product.provider} · {m.product.parserVersion}</p><p>Baseline: {m.product.baseline} · Transitions: {m.product.events.join(', ') || 'None'}</p><p>{m.product.opportunity}</p><small>{m.product.opportunityReason}</small></details>}</td><td><div className="actions">
      {m.manageable && m.status !== 'ARCHIVED' && <><button onClick={() => begin(m)}>Edit</button><button onClick={() => void act(() => m.status === 'ACTIVE' ? window.astra.pauseMonitor({ id: m.id, expectedVersion: m.version }) : window.astra.resumeMonitor({ id: m.id, expectedVersion: m.version }))}>{m.status === 'ACTIVE' ? 'Pause' : 'Resume'}</button>
        <button disabled={m.status !== 'ACTIVE' || !data.settings.storeEnabled || (m.networkAllowed === false || (!data.networkEnabled && !data.fixtureMode)) || data.reason === 'OBSERVING' || data.reason === 'READ_BUDGET_EXHAUSTED'} onClick={() => void act(() => window.astra.runMonitorNow({ id: m.id }))}>Run now</button><button onClick={() => void act(() => window.astra.archiveMonitor({ id: m.id, expectedVersion: m.version }))}>Archive</button></>}
    </div><details><summary>Run trace</summary><p className="ids">{m.id}</p>{data.history.filter(h => h.monitorId === m.id).slice(0, 5).map((h, i) => <p key={i}>{time(h.at)} · {words(h.action)}<small className="ids">{h.runId}</small></p>)}</details></td></tr>)}</tbody></table></div>}</Section></>;
}
